#
# %COPYRIGHT%
#
# %LICENSE%
#

include ../Makefile.common

PYLINT_ARGS    += --additional-builtins=_
PYTHON_MODULES += $(wildcard *.py)

all clean checkin dist doc:

.PHONY: all check checkin clean dist doc
