# Makefile for building optofs with DKMS -*-makefile-gmake-*-
#
# %COPYRIGHT%
#
# %LICENSE%
#
# $Id: $

MODNAME=pbitcorruptor
MODULE_VERSION=1

include $(src)/Makefile.common

obj-m += $(MODNAME).o
$(MODNAME)-objs := $(CORRUPTOR_OBJS)

INCLUDES += -I$(src)/
EXTRA_CFLAGS += $(INCLUDES)
