# SPDX-License-Identifier: GPL-2.0-only
# -*-makefile-*-
# vim:filetype=make
#
# %COPYRIGHT%
#
# %LICENSE%
#
# This makefile is used to generate the kernel stats header. It is not part of
# the main makefile so that it can be free to include definitions from up the
# tree.
#
# $Id$

SRC_DIR = ../../..
include $(SRC_DIR)/defines

.PHONY: all
all: $(VDO_STATS_DEPS)
	$(MAKE) -C $(VDO_STATS_DIR)
