# -*- sh -*-
#
# %COPYRIGHT%
#
# %LICENSE%
#
# DKMS configuration for the lossy module
#

PACKAGE_NAME="pbitlossy"
PACKAGE_VERSION="1"
MODULE_NAME="${PACKAGE_NAME}"
AUTOINSTALL="yes"

BUILT_MODULE_NAME[0]="pbitlossy"
DEST_MODULE_LOCATION[0]="/kernel/drivers/block/"
STRIP[0]="no"
